Add regex validation option
kyngs/LibreLogin pull request #111
Opened 2023-07-21 16:49 UTC by peteriadamgabor

Is it now possible for the operator of the serever to perform a RegeEx authentication during the registration process, which can be entered in the regex-pattern configuration field. It is also possible to return a custom error message in case of an incorrect password during registration with the custom-validation-message message key.

2023-07-22 00:01 UTC, kyngs requested changes
Hi, thanks for your interest in the repository, it is greatly appreciated. Can you please review the comments and respond to them? Thanks.

*PS: next time, please target the dev branch, I will add a CONTRIBUTING.md file soon to tackle this*

2023-07-22 13:11 UTC, peteriadamgabor commented on Plugin/src/main/java/xyz/kyngs/librelogin/common/AuthenticLibreLogin.java
> +        boolean isRegexValida = regex.equals("") || password.matches(regex);
If you look at the other variable names I used similar terminology. 
isValidLength and isForbidden. True, I have reversed the word order here as it is (it seems to me) whether the regex test itself returns a true value and not whether the regex itself that is being input is correct. 

But in fact, it works that if the password entered matches the regex the end user enters (we use this now: "^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{0,}$") then its value is true and will be returned as true. If the given configuration field is not filled, the value is returned as true. 

It is possible that the nomenclature is somewhat misleading. But the name of the function suggests that if the password entered is good, it should return true.  

P.s. Yes there was an accidental typo in the name... :D

2023-07-22 13:14 UTC, kyngs commented on Plugin/src/main/java/xyz/kyngs/librelogin/common/AuthenticLibreLogin.java
> +        boolean isRegexValida = regex.equals("") || password.matches(regex);
> If you look at the other variable names I used similar terminology. isValidLength and isForbidden. True, I have reversed the word order here as it is (it seems to me) whether the regex test itself returns a true value and not whether the regex itself that is being input is correct.
> 
> But in fact, it works that if the password entered matches the regex the end user enters (we use this now: "^(?=._[a-z])(?=._[A-Z])(?=._\d)(?=._[@$!%_?&])[A-Za-z\d@$!%_?&]{0,}$") then its value is true and will be returned as true. If the given configuration field is not filled, the value is returned as true.
> 
> It is possible that the nomenclature is somewhat misleading. But the name of the function suggests that if the password entered is good, it should return true.
> 
> P.s. Yes there was an accidental typo in the name... :D

Oh, I thought the regex was a blacklist, not a whitelist. That makes more sense now. However, I think you should make it clear in the configuration option comment.

2023-07-22 13:16 UTC, peteriadamgabor commented on Plugin/src/main/java/xyz/kyngs/librelogin/common/command/Command.java
> +        }
` if (!plugin.validPassword(password))
        {
            if(!getMessage("custom-validation-message").content().equals("")) {
                throw new InvalidCommandArgument(getMessage("custom-validation-message"));
            }
            else {
                throw new InvalidCommandArgument(getMessage("error-forbidden-password"));
            }
        }`
        
The above code snippet shows (I think) why the { } is there.

A valid point about the error-forbidden-password. originally the custom-validation-message key would have been written out during the re-registration with the /register command but that was very ugly so I chose that way instead. Pretty deceptive in hindsight. yes.

2023-07-22 13:16 UTC, peteriadamgabor commented on Plugin/src/main/java/xyz/kyngs/librelogin/common/config/MessageKeys.java
> +    );
See the comment above.

2023-07-23 09:33 UTC, kyngs commented on Plugin/src/main/java/xyz/kyngs/librelogin/common/command/Command.java
> +        }
I still don't get why it should stay. Can you remove it?

2023-07-31 11:12 UTC, kyngs commented
stale

2023-07-31 11:12 UTC, closed without merging